server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: reserva-service
          uri: http://localhost:8081
          predicates:
            - Path=/reservas/**
          filters:
            - name: CircuitBreaker
              args:
                name: reservaCB
                fallbackUri: forward:/fallback/reservas

        - id: notificacion-service
          uri: http://localhost:8084
          predicates:
            - Path=/notificaciones/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificacionCB
                fallbackUri: forward:/fallback/notificaciones
