server:
  port: 8084

spring:
  application:
    name: notificacion-service

resilience4j:
  circuitbreaker:
    instances:
      notificacionCB:
        failureRateThreshold: 50
        slidingWindowSize: 5
        waitDurationInOpenState: 10s
